export const STOCK_SET_QUOTE = 'STOCK_SET_QUOTE';
export const STOCK_SET_QUOTE_ERROR = 'STOCK_SET_QUOTE_ERROR';
export const STOCK_SET_CHART_DATA = 'STOCK_SET_CHART_DATA';
export const STOCK_SET_CHART_DATA_ERROR = 'STOCK_SET_CHART_DATA_ERROR';
export const STOCK_IS_LOADING = 'STOCK_IS_LOADING';
